### ISSUE TITLE
```Error message: 'collections.OrderedDict object' has no attribute 'github_token_for_doc_deployment'```

### ISSUE THREAD

**Issue by yaseminbridges** [hrshdhgd/sphintoxetry-cookiecutter#11]
When trying to create a project using the ```sphintoxetry-cookiecutter``` template this error message is returned:

```Error message: 'collections.OrderedDict object' has no attribute 'github_token_for_doc_deployment'```

I believe this is due to the difference in the variable name in the [cookiecutter.json](https://github.com/hrshdhgd/sphintoxetry-cookiecutter/blob/main/cookiecutter.json) where it is named  ```github_token_variable_name_for_doc_deployment```

**Comment by hrshdhgd** [comment]
Thank you for reporting this @yaseminbridges ! I have fixed the problem. Please confirm.

**Comment by yaseminbridges** [comment]
All good now!
